### ISSUE TITLE
Prebuild binaries win/osx/linux for nwjs 0.15 and sdk136

### ISSUE THREAD

**Issue by Baccanno** [greenheartgames/greenworks#81] opened 2016-07-12 09:52 UTC
[greenworks-build-nwjs0.15-sdk136.zip](https://github.com/greenheartgames/greenworks/files/359021/greenworks-build-nwjs0.15-sdk136.zip)

**Comment by hokein** [comment] 2016-07-12 20:24
@Baccanno great, thanks for that. I will probably make a new release at this weekend.

**Comment by Baccanno** [comment] 2016-07-12 21:05
You're welcome, quite a pain to build everything on 3 different systems :)

2016-07-12 22:24 GMT+02:00 Haojian Wu <notifications@github.com>:

> @Baccanno <https://github.com/Baccanno> great, thanks for that. I will
> probably make a new release at this weekend.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/greenheartgames/greenworks/issues/81#issuecomment-232168687>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADfo0F-HhHosaYdKqaWu2_LRVuExaPZoks5qU_fqgaJpZM4JKOUn>
> .
>



-- 
Michaël Picovschi, Morphiks
http://www.morphiks.com

**Comment by hokein** [comment] 2016-07-13 17:21
FYI: Just notice that nwjs v0.16.0-rc1 is released today. v0.16.0 stable version will be released after Chrome 52 stable comes out which should be happened in the following weeks. So, I'd make a release after nwjs v0.16.0 is released.

**Comment by hokein** [comment] 2016-07-23 07:28
There is a crash in nw.js v0.16.0 stable version when loading greenworks module, nwjs/nw.js#5142. :(

**Comment by MadSpyxFR** [comment] 2016-07-25 13:30
The crash happends only on macOS or for all version?

**Comment by hokein** [comment] 2016-07-25 18:34
@MadSpyxFR The crash has been fixed in master now, which is caused by a deprecated v8 API.

**Comment by Baccanno** [comment] 2016-07-29 19:21
hello, what about the prebuild binaries for nwjs 16 ?

**Comment by MadSpyxFR** [comment] 2016-08-01 11:21
@hokein Have you noticed that a nw project (even a blank "hello world") with arg "--in-process-gpu" launches only 2 nw.exe process and runs as intended only sometimes? (only on windows 7, nw.js 15/16)

**Comment by hokein** [comment] 2016-08-01 17:11
@Baccanno yeah, I have the release plan. I'd like to refine friend APIs before making a new release. The release will come in the following weeks hopefully .

@MadSpyxFR I did notice that. I would suggest you report the issue to nw.js repository directly, since we can do nothing in greenworks.

**Comment by MadSpyxFR** [comment] 2016-08-01 18:04
@hokein I know it's not related to greenworks. Thank you for confirming. I will post a report soon.

**Comment by MadSpyxFR** [comment] 2016-08-08 21:48
@hokein  [https://github.com/nwjs/nw.js/issues/5178](url)
If you want to add something or follow the thread

**Comment by MadSpyxFR** [comment] 2016-08-08 21:51
@hokein , If you want to add something [bug report](https://github.com/nwjs/nw.js/issues/5178)

**Comment by marwanhilmi** [comment] 2016-08-08 23:47
@hokein Would it be possible to add a Travis and Appveyor config to provide prebuilt binaries automatically? I can take a stab at configuring.

**Comment by hokein** [comment] 2016-08-11 20:14
@marwanhilmi Thanks for the help!

Yeah, we have thought it setup a buildbot like Travis in GitHub, but building greenworks requires SteamSDK, @patrickklug pointed out that we could't upload the Steam SDK anywhere, otherwise we might violate Steam policies, so Steam developers have to download the SDK from steam website. 

Another blocking thing is that there is no simple way to test Greenworks in buildbot as it requires Steam Client running.

**Comment by hokein** [comment] 2016-08-15 08:40
Closing it as Greenworks has v0.6.0 release now.

**Closed by hokein** 2016-08-15 08:40 UTC
