### ISSUE TITLE
Errorhandling in Windows 10 different (readFromTextFile)

### ISSUE THREAD

**Issue by janpetersen** [greenheartgames/greenworks#32] opened 2015-08-17 14:32 UTC
Hello,

The error handling under Windows 10 is a bit different with regards to the "readFromTextFile" method.

Example code:

```javascript
            greenworks.readTextFromFile(
                "fileNotFound.txt",
                function (content) {
                    alert("No error!");
                },
                function () {
                    alert("File not found!");
                }
            );
```

The file "fileNotFound.txt" does not exist.

Under Linux, Mac OS X, and any Windows version except Windows 10, this will alert "File not found!".

Under Windows 10, this will result in a "No error!" alert. The content is an empty string.

Just in case someone relies on that error function to create that missing file... like I did. ;)

**Comment by hokein** [comment] 2015-08-18 00:59
It's weird. I suspect it's a bug of Steam SDK. I sugguest you build the Greenworks with the lastest Steam SDK v1.34 and have a retry.

**Comment by hokein** [comment] 2015-09-09 13:37
@janpetersen could you verify whether the issue is fixed in v0.5.0?

**Comment by janpetersen** [comment] 2015-09-09 13:47
I'll re-test as soon as there are new release files for download. I can't compile by myself. :)

**Comment by hokein** [comment] 2016-08-15 08:41
I'm closing it as there is no more information provided. If the issue still exists, feel free to reopen it.

**Closed by hokein** 2016-08-15 08:41 UTC
Labels: bug
