### ISSUE TITLE
[0.5.0] Game crashes when opening Steam Overlay (Windows 32bit)

### ISSUE THREAD

**Issue by janpetersen** [greenheartgames/greenworks#45] opened 2015-09-07 09:36 UTC
I just downloaded your newest release and made a test build:

* 32bit application
* Running on Windows 7
* Running from Steam

Steam successfully connects to the application (I see this small overlay popup in the bottom right corner).

As soon as I hit "Shift + Tab" to open the overlay, the whole application crashes and closes itself.

These are the components I used:
* nwjs-v0.12.1-win-ia32
* steamworks_sdk_134
* greenworks-v0.5.0-nw-0.12.1

I will run some more tests to see what I can do about that.

**Comment by janpetersen** [comment] 2015-09-07 12:10
I just checked it on Windows 10: the same error. It crashes instantly.

**Comment by patrickklug** [comment] 2015-09-07 22:43
@hokein can you investigate this?

**Comment by jahrain** [comment] 2015-09-08 09:42
I confirmed this issue also occurs on Mac OS and Linux versions as well. My guess it has to do with the EventEmitter featured added. I added a greenworks.on("game-overlay-activated"), but instead crashes for me after the overlay is closed.

**Comment by hokein** [comment] 2015-09-08 09:56
I cannot reproduce it on OS X 10.10.4 with nw.js 0.12.1(Steam Client version: Built Aug 19, 2015), the game overlay and `game-overlay-activated` event works as expected.

![gameoverlay](https://cloud.githubusercontent.com/assets/2557445/9731968/e55b74a6-5652-11e5-9474-ceb585cb4816.gif)

**Comment by jahrain** [comment] 2015-09-08 13:20
I think the MacOS and Linux issues are unrelated to this. I updated my comment.

**Comment by janpetersen** [comment] 2015-09-09 08:12
@hokein How can you open the overlay, when it is disabled?
"isGameOverlayEnabled: false"

With that set to "false", you should not be able to open it at all.

**Comment by hokein** [comment] 2015-09-09 08:34
@janpetersen 

I just type `shift+tab` to activate/deactivate the gameoverlay feature. 

From the Steam SDK words about isGameOverlayEnabled:

>// Returns true if the overlay is running & the user can access it. The overlay process could take a few seconds to start & hook the game process, so this function will initially return false while the overlay is loading.

The `isGameOverlayEnabled:false` result showing in my screenshot runs at the launch time of the application, and the overlay process doesn't start yet. But when the game overlay is shown, the API returns `true` indeed.

**Comment by janpetersen** [comment] 2015-09-09 08:40
Thanks for your reply. :)

I took a look into the source code, two questions:

steam_client.h::49: "steam_shutfown_" (notice the "f")
Is that typo critical? I could not get the shutdown event to work, at least my "alert('shutdown!');" was not triggered. Instead, the game crashed and quit.

steam_client.h::29: void RemoveObserver(Observer* observer);
I could not find an implementation of that method, or is it a standard method? Unfortunately, I'm no C++ developer. Might be a stupid question.

I guess there might be some bug related to the new event emitter thing.

**Comment by hokein** [comment] 2015-09-09 08:53
>steam_client.h::49: "steam_shutfown_" (notice the "f")
Is that typo critical? I could not get the shutdown event to work, at least my "alert('shutdown!');" was not triggered. Instead, the game crashed and quit.

Oh, it is my typo. But it won't effect on the shutfown event. The `shutdown` works on OS X, the game will recevie the event when user is closing Steam Client during the game is still running.

>steam_client.h::29: void RemoveObserver(Observer* observer);
>I could not find an implementation of that method, or is it a standard method? Unfortunately, I'm no C++ developer. Might be a stupid question.

Didn't notice that. This function is not needed, should be removed.

But both these two questions are not related to the issue of new event emitter. Thanks for pointing out these!

**Comment by janpetersen** [comment] 2015-09-09 09:44
Okay, that explains a lot. :)

I just created a pull request, in which I fixed the nw.js sample which was apparently broken.

Now the sample works, to the extent, that the application *crashes* as soon as I want to open the game overlay (on Windows).

Before opening the overlay, I get to see the following:

![hello-greenworks](https://cloud.githubusercontent.com/assets/4749092/9758626/17d7293a-56e8-11e5-91be-16b18befcc27.png)

Do you have a Windows PC to test it there?

**Comment by hokein** [comment] 2015-09-09 10:11
Thanks for it!

> Do you have a Windows PC to test it there?

I wish too. But right now I don't have a windows machine around.

**Comment by janpetersen** [comment] 2015-09-09 10:16
In that case, it's a bit risky to publish new releases for Windows that you didn't even test. :)

You might definitively want to get access to a Windows PC and test things. Perhaps even a virtual machine on your Mac will do.

**Comment by hokein** [comment] 2015-09-09 10:21
> In that case, it's a bit risky to publish new releases for Windows that you didn't even test. :)

Indeed, I build, run the sample to make sure it works on Windows/Linux/OS X for each release greenworks version.  But for gameoverly feature, I test it on OS X and it works, so I have a assumption it work on other other platforms.  I moved to a new tempoary location yesterday, so I only take my laptop.

**Comment by jahrain** [comment] 2015-09-09 12:44
I managed to trace the issue down while running a debugger on a Windows. Node is crashing while trying to allocate a new V8 object when the callback fires and there is no scope created. Why this works on MacOS baffles me, it could be just silent memory corruption happening or something. I fixed it with my PR here: https://github.com/greenheartgames/greenworks/pull/47

**Comment by hokein** [comment] 2015-09-09 13:36
The `game-overlay-activated` crash issue is fixed in #47(thanks for @jahrain).

**Closed by hokein** 2015-09-09 13:36 UTC

**Comment by janpetersen** [comment] 2015-09-10 13:37
@hokein Could you please provide a new release for these fixes? I can't build the greenworks module by myself for the various platforms.

**Comment by hokein** [comment] 2015-09-12 14:54
@janpetersen Greenworks v0.5.2 has been released now. You can try it.

**Comment by janpetersen** [comment] 2015-09-14 08:00
Thank you very much, I will check it out today! :)
