### ISSUE TITLE
Request for Integration of ISteamInventory Interface.

### ISSUE THREAD

**Issue by LHYLHY-git** [greenheartgames/greenworks#328] opened 2024-07-16 07:45 UTC
It has been noted in discussions dating back to 2019, [#243](https://github.com/greenheartgames/greenworks/issues/243), that the ISteamInventory interface is absent from Greenworks. 

Judging by some of the games that have been released recently, the popularity of the Steam inventory service is highly increasing. And many developers are interested in it, including me.

So could you please add ISteamInventory interface in Greenworks? Appreciate your hard work.

https://partner.steamgames.com/doc/api/ISteamInventory

**Comment by hokein** [comment] 2024-07-27 06:56
Duplicate of https://github.com/greenheartgames/greenworks/issues/243.

**Closed by hokein** 2024-07-27 06:56 UTC
