### ISSUE TITLE
Build Error (macOS)

### ISSUE THREAD

**Issue by oyed** [greenheartgames/greenworks#144] opened 2017-06-24 09:44 UTC
Building with `nw-gyp build --target=0.23.4` and getting the following error:

```
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.4.0
gyp info using node@8.1.2 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/minizip/deps/zlib/contrib/minizip/ioapi.o
  CC(target) Release/obj.target/minizip/deps/zlib/contrib/minizip/unzip.o
  CC(target) Release/obj.target/minizip/deps/zlib/contrib/minizip/zip.o
  LIBTOOL-STATIC Release/minizip.a
  CC(target) Release/obj.target/zlib/deps/zlib/adler32.o
  CC(target) Release/obj.target/zlib/deps/zlib/compress.o
  CC(target) Release/obj.target/zlib/deps/zlib/crc32.o
  CC(target) Release/obj.target/zlib/deps/zlib/deflate.o
  CC(target) Release/obj.target/zlib/deps/zlib/gzclose.o
  CC(target) Release/obj.target/zlib/deps/zlib/gzlib.o
  CC(target) Release/obj.target/zlib/deps/zlib/gzread.o
  CC(target) Release/obj.target/zlib/deps/zlib/gzwrite.o
  CC(target) Release/obj.target/zlib/deps/zlib/infback.o
  CC(target) Release/obj.target/zlib/deps/zlib/inffast.o
  CC(target) Release/obj.target/zlib/deps/zlib/inflate.o
../deps/zlib/inflate.c:1475:61: warning: shifting a negative signed value is
      undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.
  CC(target) Release/obj.target/zlib/deps/zlib/inftrees.o
  CC(target) Release/obj.target/zlib/deps/zlib/trees.o
  CC(target) Release/obj.target/zlib/deps/zlib/uncompr.o
  CC(target) Release/obj.target/zlib/deps/zlib/zutil.o
  LIBTOOL-STATIC Release/chrome_zlib.a
  CXX(target) Release/obj.target/greenworks-osx64/src/api/greenworks_api_utils.o
  CXX(target) Release/obj.target/greenworks-osx64/src/api/steam_api_achievement.o
  CXX(target) Release/obj.target/greenworks-osx64/src/api/steam_api_auth.o
  CXX(target) Release/obj.target/greenworks-osx64/src/api/steam_api_cloud.o
  CXX(target) Release/obj.target/greenworks-osx64/src/api/steam_api_dlc.o
  CXX(target) Release/obj.target/greenworks-osx64/src/api/steam_api_friends.o
  CXX(target) Release/obj.target/greenworks-osx64/src/api/steam_api_settings.o
  CXX(target) Release/obj.target/greenworks-osx64/src/api/steam_api_stats.o
  CXX(target) Release/obj.target/greenworks-osx64/src/api/steam_api_workshop.o
  CXX(target) Release/obj.target/greenworks-osx64/src/greenworks_api.o
  CXX(target) Release/obj.target/greenworks-osx64/src/greenworks_async_workers.o
  CXX(target) Release/obj.target/greenworks-osx64/src/greenworks_unzip.o
  CXX(target) Release/obj.target/greenworks-osx64/src/greenworks_utils.o
  CXX(target) Release/obj.target/greenworks-osx64/src/greenworks_workshop_workers.o
  CXX(target) Release/obj.target/greenworks-osx64/src/greenworks_zip.o
  CXX(target) Release/obj.target/greenworks-osx64/src/steam_async_worker.o
  CXX(target) Release/obj.target/greenworks-osx64/src/steam_client.o
  CXX(target) Release/obj.target/greenworks-osx64/src/steam_event.o
../src/steam_event.cc:110:16: error: use of undeclared identifier 'utils'
      Nan::New(utils::uint64ToString(OrderID)).ToLocalChecked(),
               ^
1 error generated.
make: *** [Release/obj.target/greenworks-osx64/src/steam_event.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/tom/.nvm/versions/node/v8.1.2/lib/node_modules/nw-gyp/lib/build.js:294:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/tom/.nvm/versions/node/v8.1.2/bin/node" "/Users/tom/.nvm/versions/node/v8.1.2/bin/nw-gyp" "build" "--target=0.23.4"
gyp ERR! cwd /Users/tom/Downloads/greenworks-master
gyp ERR! node -v v8.1.2
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by hokein** [comment] 2017-06-24 11:13
It is caused by a missing header. It is fixed now. Thanks for the report.

**Closed by hokein** 2017-06-24 11:13 UTC

**Comment by MadSpyxFR** [comment] 2017-06-24 17:21
Yeah I forgot the header :x guilty ^^
